apiVersion: v1
kind: ConfigMap
metadata:
  name: coredns-custom
  namespace: kube-system
data:
  mathtrail.override: |
    rewrite name mathtrail.localhost traefik.kube-system.svc.cluster.local answer auto
    rewrite name minio.mathtrail.localhost traefik.kube-system.svc.cluster.local answer auto
