---
- name: Create k3d development cluster
  hosts: localhost
  gather_facts: true

  vars:
    k3d_registries_config: "{{ playbook_dir }}/../registries.yaml"

  roles:
    - role: k3d_cluster
      k3d_cluster_state: present
